"use client"
import Head from "next/head";
import { useSession, signIn } from "next-auth/react"

import styles from "./index.module.css";

export default function Home() {
  const { data: session } = useSession()

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main className={styles.main}>
          <div style={{ color: 'white' }}>
            Hello! 
            
            <button onClick={() => signIn()}>
              Sign In 
            </button>

            <pre>
              {JSON.stringify(session)}
            </pre>
          </div>
        </main>
    </>
  );
}
